"""Generate a local dev CA + per-bank client certs + a broker cert for
docker-compose.yml's mTLS Kafka listener (docs/SECURITY.md SS3.8).

    python scripts/generate_dev_certs.py [BANK_ID ...]

Defaults to BANK-A, BANK-B, BANK-EVIL if no bank IDs are given (matching the
identities the rest of this repo's tests and demo already use). Re-run any
time to regenerate everything from scratch -- outputs are placed under
./certs/, which is gitignored; nothing here is meant to be committed or to
outlive one developer's machine.

Dev-only, stated plainly: keys are unencrypted PEM on disk, the CA key sits
right next to the leaf keys it signs, and the CA has no revocation mechanism.
A real deployment needs the CA key held by an actual (ideally offline or
HSM-backed -- see SS3.6, still open) authority, not generated by the same
script that also mints every leaf cert.
"""

from __future__ import annotations

import datetime
import ipaddress
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

CERTS_DIR = Path(__file__).resolve().parent.parent / "certs"
KEY_SIZE = 2048
VALID_DAYS = 825  # matches common CA/Browser Forum leaf-cert practice
DEFAULT_BANKS = ("BANK-A", "BANK-B", "BANK-EVIL")


def _new_key() -> rsa.RSAPrivateKey:
    return rsa.generate_private_key(public_exponent=65537, key_size=KEY_SIZE)


def _write_pem(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    path.chmod(0o600)


def _key_pem(key: rsa.RSAPrivateKey) -> bytes:
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )


def _cert_pem(cert: x509.Certificate) -> bytes:
    return cert.public_bytes(serialization.Encoding.PEM)


def generate_ca() -> tuple[rsa.RSAPrivateKey, x509.Certificate]:
    key = _new_key()
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "ARIS Dev CA")])
    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(minutes=5))
        .not_valid_after(now + datetime.timedelta(days=VALID_DAYS))
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=False,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .sign(key, hashes.SHA256())
    )
    return key, cert


def _sign_leaf(
    common_name: str,
    ca_key: rsa.RSAPrivateKey,
    ca_cert: x509.Certificate,
    san: list[x509.GeneralName],
) -> tuple[rsa.RSAPrivateKey, x509.Certificate]:
    key = _new_key()
    now = datetime.datetime.now(datetime.timezone.utc)
    builder = (
        x509.CertificateBuilder()
        .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common_name)]))
        .issuer_name(ca_cert.subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(minutes=5))
        .not_valid_after(now + datetime.timedelta(days=VALID_DAYS))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=True,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(
            x509.ExtendedKeyUsage([x509.OID_SERVER_AUTH, x509.OID_CLIENT_AUTH]),
            critical=False,
        )
    )
    if san:
        builder = builder.add_extension(x509.SubjectAlternativeName(san), critical=False)
    cert = builder.sign(ca_key, hashes.SHA256())
    return key, cert


def generate_broker_cert(
    ca_key: rsa.RSAPrivateKey, ca_cert: x509.Certificate
) -> tuple[rsa.RSAPrivateKey, x509.Certificate]:
    san: list[x509.GeneralName] = [
        x509.DNSName("kafka"),
        x509.DNSName("localhost"),
        x509.IPAddress(ipaddress.ip_address("127.0.0.1")),
    ]
    return _sign_leaf("kafka-broker", ca_key, ca_cert, san)


def generate_bank_cert(
    bank_id: str, ca_key: rsa.RSAPrivateKey, ca_cert: x509.Certificate
) -> tuple[rsa.RSAPrivateKey, x509.Certificate]:
    # No SAN: a client cert's identity is its CN, matched against
    # ssl.principal.mapping.rules on the broker (docs/SECURITY.md SS3.8).
    return _sign_leaf(bank_id, ca_key, ca_cert, san=[])


def main(argv: list[str]) -> int:
    bank_ids = argv or list(DEFAULT_BANKS)

    ca_key, ca_cert = generate_ca()
    _write_pem(CERTS_DIR / "ca.pem", _cert_pem(ca_cert))
    _write_pem(CERTS_DIR / "ca-key.pem", _key_pem(ca_key))

    broker_key, broker_cert = generate_broker_cert(ca_key, ca_cert)
    _write_pem(CERTS_DIR / "broker" / "cert.pem", _cert_pem(broker_cert))
    _write_pem(CERTS_DIR / "broker" / "key.pem", _key_pem(broker_key))
    # Kafka's PEM keystore type wants certificate chain + key concatenated in
    # one file (KIP-651); truststore is just the CA cert on its own.
    _write_pem(
        CERTS_DIR / "broker" / "keystore.pem",
        _cert_pem(broker_cert) + _key_pem(broker_key),
    )

    for bank_id in bank_ids:
        key, cert = generate_bank_cert(bank_id, ca_key, ca_cert)
        out = CERTS_DIR / "banks" / bank_id
        _write_pem(out / "cert.pem", _cert_pem(cert))
        _write_pem(out / "key.pem", _key_pem(key))
        print(f"generated certs/banks/{bank_id}/{{cert,key}}.pem (CN={bank_id})")

    print("generated certs/ca.pem, certs/broker/{cert,key,keystore}.pem")
    print(f"all certs valid {VALID_DAYS} days from now; re-run this script to rotate them")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
